kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/cuisongliu/docker-install

steps:
- name: build
  image: golang:1.11.3
  commands:
      - go build -o docker-install

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: docker-install
    title: ${DRONE_TAG}
    note: Note.md
  when:
     event:
     - tag
