kind: pipeline
name: default
workspace:
    base: /go
    path: src/github.com/cuisongliu/docker-install

steps:
- name: build
  image: golang:1.11.3
  commands:
      - go build -o docker-install

- name: publish-hub
  image: plugins/docker
  settings:
    repo: cuisongliu/docker-install
    tags: ${DRONE_TAG=latest}
    username:
      from_secret: docker-hub-user
    dockerfile: Dockerfile
    password:
      from_secret: docker-hub-pass

- name: publish
  image: plugins/github-release
  settings:
    api_key:
        from_secret: git-release-token
    files: sealos
    title: ${DRONE_TAG}
    note: Note.md
  when:
     event:
     - tag
