before:
  hooks:
    - rm -rf install/command/*.json && touch install/command/docker.json && touch install/command/containerd.json
    - make generator-containerd
    - make generator-docker
    - make generator
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
#    ldflags:
#      - -s -w -X github.com/sealyun-market/marketctl/cmd.Version={{.Version}} -X github.com/sealyun-market/marketctl/cmd.Githash={{.ShortCommit}} -X github.com/sealyun-market/marketctl/cmd.Buildstamp={{.Date}} -X github.com/sealyun-market/marketctl/cmd.Author=goreleaser

#archives:
#  - replacements:
#      darwin: darwin
#      linux: linux
#      windows: windows
#      amd64: amd64
#      arm64: arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

#dockers:
#  -
#    goos: linux
#
#    goarch: amd64
#
#    binaries:
#      - marketctl
#
#    image_templates:
#      - "louisehong/{{.ProjectName}}:latest"
#      - "louisehong/{{.ProjectName}}:{{.Tag}}"
#
#    dockerfile: Dockerfile.hub
#    extra_files:
#      - scripts/entrypoint.sh
