name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: build --snapshot --rm-dist  --timeout=1h

    - name: Build binareies to oss
      run: |
        echo ${{ secrets.OSS_CONFIG }} |base64 --decode >> .ossutilconfig
        wget http://gosspublic.alicdn.com/ossutil/1.6.19/ossutil64  && chmod 755 ossutil64
        ./ossutil64 -c .ossutilconfig cp -r -f dist/container-install_darwin_amd64 oss://cuisongliu/container-install/latest/darwin_amd64
        ./ossutil64 -c .ossutilconfig cp -r -f dist/container-install_linux_amd64 oss://cuisongliu/container-install/latest/linux_amd64
        ./ossutil64 -c .ossutilconfig cp -r -f dist/container-install_linux_arm64 oss://cuisongliu/container-install/latest/linux_arm64
        ./ossutil64 -c .ossutilconfig cp -r -f dist/container-install_windows_amd64 oss://cuisongliu/container-install/latest/windows_amd64
